/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.jivesoftware.community.cloudalytics.schemata;  
@SuppressWarnings("all")
/** ****** BEGIN CONTENT ACTIVITY DEFINITIONS ********* */
@org.apache.avro.specific.AvroGenerated
public class Comment extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8633423722301778043L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Comment\",\"namespace\":\"com.jivesoftware.community.cloudalytics.schemata\",\"doc\":\"****** BEGIN CONTENT ACTIVITY DEFINITIONS *********\",\"fields\":[{\"name\":\"parentCommentId\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"parentComment\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.Long parentCommentId;
  @Deprecated public java.lang.CharSequence parentComment;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Comment() {}

  /**
   * All-args constructor.
   */
  public Comment(java.lang.Long parentCommentId, java.lang.CharSequence parentComment) {
    this.parentCommentId = parentCommentId;
    this.parentComment = parentComment;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return parentCommentId;
    case 1: return parentComment;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: parentCommentId = (java.lang.Long)value$; break;
    case 1: parentComment = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'parentCommentId' field.
   */
  public java.lang.Long getParentCommentId() {
    return parentCommentId;
  }

  /**
   * Sets the value of the 'parentCommentId' field.
   * @param value the value to set.
   */
  public void setParentCommentId(java.lang.Long value) {
    this.parentCommentId = value;
  }

  /**
   * Gets the value of the 'parentComment' field.
   */
  public java.lang.CharSequence getParentComment() {
    return parentComment;
  }

  /**
   * Sets the value of the 'parentComment' field.
   * @param value the value to set.
   */
  public void setParentComment(java.lang.CharSequence value) {
    this.parentComment = value;
  }

  /**
   * Creates a new Comment RecordBuilder.
   * @return A new Comment RecordBuilder
   */
  public static com.jivesoftware.community.cloudalytics.schemata.Comment.Builder newBuilder() {
    return new com.jivesoftware.community.cloudalytics.schemata.Comment.Builder();
  }
  
  /**
   * Creates a new Comment RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Comment RecordBuilder
   */
  public static com.jivesoftware.community.cloudalytics.schemata.Comment.Builder newBuilder(com.jivesoftware.community.cloudalytics.schemata.Comment.Builder other) {
    return new com.jivesoftware.community.cloudalytics.schemata.Comment.Builder(other);
  }
  
  /**
   * Creates a new Comment RecordBuilder by copying an existing Comment instance.
   * @param other The existing instance to copy.
   * @return A new Comment RecordBuilder
   */
  public static com.jivesoftware.community.cloudalytics.schemata.Comment.Builder newBuilder(com.jivesoftware.community.cloudalytics.schemata.Comment other) {
    return new com.jivesoftware.community.cloudalytics.schemata.Comment.Builder(other);
  }
  
  /**
   * RecordBuilder for Comment instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Comment>
    implements org.apache.avro.data.RecordBuilder<Comment> {

    private java.lang.Long parentCommentId;
    private java.lang.CharSequence parentComment;

    /** Creates a new Builder */
    private Builder() {
      super(com.jivesoftware.community.cloudalytics.schemata.Comment.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.jivesoftware.community.cloudalytics.schemata.Comment.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.parentCommentId)) {
        this.parentCommentId = data().deepCopy(fields()[0].schema(), other.parentCommentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.parentComment)) {
        this.parentComment = data().deepCopy(fields()[1].schema(), other.parentComment);
        fieldSetFlags()[1] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing Comment instance
     * @param other The existing instance to copy.
     */
    private Builder(com.jivesoftware.community.cloudalytics.schemata.Comment other) {
            super(com.jivesoftware.community.cloudalytics.schemata.Comment.SCHEMA$);
      if (isValidValue(fields()[0], other.parentCommentId)) {
        this.parentCommentId = data().deepCopy(fields()[0].schema(), other.parentCommentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.parentComment)) {
        this.parentComment = data().deepCopy(fields()[1].schema(), other.parentComment);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'parentCommentId' field.
      * @return The value.
      */
    public java.lang.Long getParentCommentId() {
      return parentCommentId;
    }

    /**
      * Sets the value of the 'parentCommentId' field.
      * @param value The value of 'parentCommentId'.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.schemata.Comment.Builder setParentCommentId(java.lang.Long value) {
      validate(fields()[0], value);
      this.parentCommentId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'parentCommentId' field has been set.
      * @return True if the 'parentCommentId' field has been set, false otherwise.
      */
    public boolean hasParentCommentId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'parentCommentId' field.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.schemata.Comment.Builder clearParentCommentId() {
      parentCommentId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'parentComment' field.
      * @return The value.
      */
    public java.lang.CharSequence getParentComment() {
      return parentComment;
    }

    /**
      * Sets the value of the 'parentComment' field.
      * @param value The value of 'parentComment'.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.schemata.Comment.Builder setParentComment(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.parentComment = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'parentComment' field has been set.
      * @return True if the 'parentComment' field has been set, false otherwise.
      */
    public boolean hasParentComment() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'parentComment' field.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.schemata.Comment.Builder clearParentComment() {
      parentComment = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Comment build() {
      try {
        Comment record = new Comment();
        record.parentCommentId = fieldSetFlags()[0] ? this.parentCommentId : (java.lang.Long) defaultValue(fields()[0]);
        record.parentComment = fieldSetFlags()[1] ? this.parentComment : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
