/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.jivesoftware.community.cloudalytics.event.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroAppLoad extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4102927109674316703L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroAppLoad\",\"namespace\":\"com.jivesoftware.community.cloudalytics.event.avro\",\"fields\":[{\"name\":\"appName\",\"type\":{\"type\":\"string\",\"order\":\"ignore\"}},{\"name\":\"appURL\",\"type\":\"string\"},{\"name\":\"extensionUUID\",\"type\":\"string\"},{\"name\":\"isSynthetic\",\"type\":\"boolean\"},{\"name\":\"associatedObjectType\",\"type\":\"string\"},{\"name\":\"associatedObjectId\",\"type\":\"long\"},{\"name\":\"associatedName\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence appName;
  @Deprecated public java.lang.CharSequence appURL;
  @Deprecated public java.lang.CharSequence extensionUUID;
  @Deprecated public boolean isSynthetic;
  @Deprecated public java.lang.CharSequence associatedObjectType;
  @Deprecated public long associatedObjectId;
  @Deprecated public java.lang.CharSequence associatedName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public AvroAppLoad() {}

  /**
   * All-args constructor.
   */
  public AvroAppLoad(java.lang.CharSequence appName, java.lang.CharSequence appURL, java.lang.CharSequence extensionUUID, java.lang.Boolean isSynthetic, java.lang.CharSequence associatedObjectType, java.lang.Long associatedObjectId, java.lang.CharSequence associatedName) {
    this.appName = appName;
    this.appURL = appURL;
    this.extensionUUID = extensionUUID;
    this.isSynthetic = isSynthetic;
    this.associatedObjectType = associatedObjectType;
    this.associatedObjectId = associatedObjectId;
    this.associatedName = associatedName;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return appName;
    case 1: return appURL;
    case 2: return extensionUUID;
    case 3: return isSynthetic;
    case 4: return associatedObjectType;
    case 5: return associatedObjectId;
    case 6: return associatedName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: appName = (java.lang.CharSequence)value$; break;
    case 1: appURL = (java.lang.CharSequence)value$; break;
    case 2: extensionUUID = (java.lang.CharSequence)value$; break;
    case 3: isSynthetic = (java.lang.Boolean)value$; break;
    case 4: associatedObjectType = (java.lang.CharSequence)value$; break;
    case 5: associatedObjectId = (java.lang.Long)value$; break;
    case 6: associatedName = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'appName' field.
   */
  public java.lang.CharSequence getAppName() {
    return appName;
  }

  /**
   * Sets the value of the 'appName' field.
   * @param value the value to set.
   */
  public void setAppName(java.lang.CharSequence value) {
    this.appName = value;
  }

  /**
   * Gets the value of the 'appURL' field.
   */
  public java.lang.CharSequence getAppURL() {
    return appURL;
  }

  /**
   * Sets the value of the 'appURL' field.
   * @param value the value to set.
   */
  public void setAppURL(java.lang.CharSequence value) {
    this.appURL = value;
  }

  /**
   * Gets the value of the 'extensionUUID' field.
   */
  public java.lang.CharSequence getExtensionUUID() {
    return extensionUUID;
  }

  /**
   * Sets the value of the 'extensionUUID' field.
   * @param value the value to set.
   */
  public void setExtensionUUID(java.lang.CharSequence value) {
    this.extensionUUID = value;
  }

  /**
   * Gets the value of the 'isSynthetic' field.
   */
  public java.lang.Boolean getIsSynthetic() {
    return isSynthetic;
  }

  /**
   * Sets the value of the 'isSynthetic' field.
   * @param value the value to set.
   */
  public void setIsSynthetic(java.lang.Boolean value) {
    this.isSynthetic = value;
  }

  /**
   * Gets the value of the 'associatedObjectType' field.
   */
  public java.lang.CharSequence getAssociatedObjectType() {
    return associatedObjectType;
  }

  /**
   * Sets the value of the 'associatedObjectType' field.
   * @param value the value to set.
   */
  public void setAssociatedObjectType(java.lang.CharSequence value) {
    this.associatedObjectType = value;
  }

  /**
   * Gets the value of the 'associatedObjectId' field.
   */
  public java.lang.Long getAssociatedObjectId() {
    return associatedObjectId;
  }

  /**
   * Sets the value of the 'associatedObjectId' field.
   * @param value the value to set.
   */
  public void setAssociatedObjectId(java.lang.Long value) {
    this.associatedObjectId = value;
  }

  /**
   * Gets the value of the 'associatedName' field.
   */
  public java.lang.CharSequence getAssociatedName() {
    return associatedName;
  }

  /**
   * Sets the value of the 'associatedName' field.
   * @param value the value to set.
   */
  public void setAssociatedName(java.lang.CharSequence value) {
    this.associatedName = value;
  }

  /**
   * Creates a new AvroAppLoad RecordBuilder.
   * @return A new AvroAppLoad RecordBuilder
   */
  public static com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.Builder newBuilder() {
    return new com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.Builder();
  }
  
  /**
   * Creates a new AvroAppLoad RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroAppLoad RecordBuilder
   */
  public static com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.Builder newBuilder(com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.Builder other) {
    return new com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.Builder(other);
  }
  
  /**
   * Creates a new AvroAppLoad RecordBuilder by copying an existing AvroAppLoad instance.
   * @param other The existing instance to copy.
   * @return A new AvroAppLoad RecordBuilder
   */
  public static com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.Builder newBuilder(com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad other) {
    return new com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.Builder(other);
  }
  
  /**
   * RecordBuilder for AvroAppLoad instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroAppLoad>
    implements org.apache.avro.data.RecordBuilder<AvroAppLoad> {

    private java.lang.CharSequence appName;
    private java.lang.CharSequence appURL;
    private java.lang.CharSequence extensionUUID;
    private boolean isSynthetic;
    private java.lang.CharSequence associatedObjectType;
    private long associatedObjectId;
    private java.lang.CharSequence associatedName;

    /** Creates a new Builder */
    private Builder() {
      super(com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.appName)) {
        this.appName = data().deepCopy(fields()[0].schema(), other.appName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.appURL)) {
        this.appURL = data().deepCopy(fields()[1].schema(), other.appURL);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.extensionUUID)) {
        this.extensionUUID = data().deepCopy(fields()[2].schema(), other.extensionUUID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.isSynthetic)) {
        this.isSynthetic = data().deepCopy(fields()[3].schema(), other.isSynthetic);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.associatedObjectType)) {
        this.associatedObjectType = data().deepCopy(fields()[4].schema(), other.associatedObjectType);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.associatedObjectId)) {
        this.associatedObjectId = data().deepCopy(fields()[5].schema(), other.associatedObjectId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.associatedName)) {
        this.associatedName = data().deepCopy(fields()[6].schema(), other.associatedName);
        fieldSetFlags()[6] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing AvroAppLoad instance
     * @param other The existing instance to copy.
     */
    private Builder(com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad other) {
            super(com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.SCHEMA$);
      if (isValidValue(fields()[0], other.appName)) {
        this.appName = data().deepCopy(fields()[0].schema(), other.appName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.appURL)) {
        this.appURL = data().deepCopy(fields()[1].schema(), other.appURL);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.extensionUUID)) {
        this.extensionUUID = data().deepCopy(fields()[2].schema(), other.extensionUUID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.isSynthetic)) {
        this.isSynthetic = data().deepCopy(fields()[3].schema(), other.isSynthetic);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.associatedObjectType)) {
        this.associatedObjectType = data().deepCopy(fields()[4].schema(), other.associatedObjectType);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.associatedObjectId)) {
        this.associatedObjectId = data().deepCopy(fields()[5].schema(), other.associatedObjectId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.associatedName)) {
        this.associatedName = data().deepCopy(fields()[6].schema(), other.associatedName);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'appName' field.
      * @return The value.
      */
    public java.lang.CharSequence getAppName() {
      return appName;
    }

    /**
      * Sets the value of the 'appName' field.
      * @param value The value of 'appName'.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.Builder setAppName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.appName = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'appName' field has been set.
      * @return True if the 'appName' field has been set, false otherwise.
      */
    public boolean hasAppName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'appName' field.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.Builder clearAppName() {
      appName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'appURL' field.
      * @return The value.
      */
    public java.lang.CharSequence getAppURL() {
      return appURL;
    }

    /**
      * Sets the value of the 'appURL' field.
      * @param value The value of 'appURL'.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.Builder setAppURL(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.appURL = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'appURL' field has been set.
      * @return True if the 'appURL' field has been set, false otherwise.
      */
    public boolean hasAppURL() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'appURL' field.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.Builder clearAppURL() {
      appURL = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'extensionUUID' field.
      * @return The value.
      */
    public java.lang.CharSequence getExtensionUUID() {
      return extensionUUID;
    }

    /**
      * Sets the value of the 'extensionUUID' field.
      * @param value The value of 'extensionUUID'.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.Builder setExtensionUUID(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.extensionUUID = value;
      fieldSetFlags()[2] = true;
      return this; 
    }

    /**
      * Checks whether the 'extensionUUID' field has been set.
      * @return True if the 'extensionUUID' field has been set, false otherwise.
      */
    public boolean hasExtensionUUID() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'extensionUUID' field.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.Builder clearExtensionUUID() {
      extensionUUID = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'isSynthetic' field.
      * @return The value.
      */
    public java.lang.Boolean getIsSynthetic() {
      return isSynthetic;
    }

    /**
      * Sets the value of the 'isSynthetic' field.
      * @param value The value of 'isSynthetic'.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.Builder setIsSynthetic(boolean value) {
      validate(fields()[3], value);
      this.isSynthetic = value;
      fieldSetFlags()[3] = true;
      return this; 
    }

    /**
      * Checks whether the 'isSynthetic' field has been set.
      * @return True if the 'isSynthetic' field has been set, false otherwise.
      */
    public boolean hasIsSynthetic() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'isSynthetic' field.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.Builder clearIsSynthetic() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'associatedObjectType' field.
      * @return The value.
      */
    public java.lang.CharSequence getAssociatedObjectType() {
      return associatedObjectType;
    }

    /**
      * Sets the value of the 'associatedObjectType' field.
      * @param value The value of 'associatedObjectType'.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.Builder setAssociatedObjectType(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.associatedObjectType = value;
      fieldSetFlags()[4] = true;
      return this; 
    }

    /**
      * Checks whether the 'associatedObjectType' field has been set.
      * @return True if the 'associatedObjectType' field has been set, false otherwise.
      */
    public boolean hasAssociatedObjectType() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'associatedObjectType' field.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.Builder clearAssociatedObjectType() {
      associatedObjectType = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'associatedObjectId' field.
      * @return The value.
      */
    public java.lang.Long getAssociatedObjectId() {
      return associatedObjectId;
    }

    /**
      * Sets the value of the 'associatedObjectId' field.
      * @param value The value of 'associatedObjectId'.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.Builder setAssociatedObjectId(long value) {
      validate(fields()[5], value);
      this.associatedObjectId = value;
      fieldSetFlags()[5] = true;
      return this; 
    }

    /**
      * Checks whether the 'associatedObjectId' field has been set.
      * @return True if the 'associatedObjectId' field has been set, false otherwise.
      */
    public boolean hasAssociatedObjectId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'associatedObjectId' field.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.Builder clearAssociatedObjectId() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'associatedName' field.
      * @return The value.
      */
    public java.lang.CharSequence getAssociatedName() {
      return associatedName;
    }

    /**
      * Sets the value of the 'associatedName' field.
      * @param value The value of 'associatedName'.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.Builder setAssociatedName(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.associatedName = value;
      fieldSetFlags()[6] = true;
      return this; 
    }

    /**
      * Checks whether the 'associatedName' field has been set.
      * @return True if the 'associatedName' field has been set, false otherwise.
      */
    public boolean hasAssociatedName() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'associatedName' field.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.event.avro.AvroAppLoad.Builder clearAssociatedName() {
      associatedName = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    public AvroAppLoad build() {
      try {
        AvroAppLoad record = new AvroAppLoad();
        record.appName = fieldSetFlags()[0] ? this.appName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.appURL = fieldSetFlags()[1] ? this.appURL : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.extensionUUID = fieldSetFlags()[2] ? this.extensionUUID : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.isSynthetic = fieldSetFlags()[3] ? this.isSynthetic : (java.lang.Boolean) defaultValue(fields()[3]);
        record.associatedObjectType = fieldSetFlags()[4] ? this.associatedObjectType : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.associatedObjectId = fieldSetFlags()[5] ? this.associatedObjectId : (java.lang.Long) defaultValue(fields()[5]);
        record.associatedName = fieldSetFlags()[6] ? this.associatedName : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
