/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.jivesoftware.community.cloudalytics.event.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroPlayboxQuest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -606184696700730079L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroPlayboxQuest\",\"namespace\":\"com.jivesoftware.community.cloudalytics.event.avro\",\"fields\":[{\"name\":\"questId\",\"type\":{\"type\":\"string\",\"order\":\"ignore\"}},{\"name\":\"taskId\",\"type\":\"string\"},{\"name\":\"secret\",\"type\":\"string\"},{\"name\":\"isApiRequest\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence questId;
  @Deprecated public java.lang.CharSequence taskId;
  @Deprecated public java.lang.CharSequence secret;
  @Deprecated public boolean isApiRequest;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public AvroPlayboxQuest() {}

  /**
   * All-args constructor.
   */
  public AvroPlayboxQuest(java.lang.CharSequence questId, java.lang.CharSequence taskId, java.lang.CharSequence secret, java.lang.Boolean isApiRequest) {
    this.questId = questId;
    this.taskId = taskId;
    this.secret = secret;
    this.isApiRequest = isApiRequest;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return questId;
    case 1: return taskId;
    case 2: return secret;
    case 3: return isApiRequest;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: questId = (java.lang.CharSequence)value$; break;
    case 1: taskId = (java.lang.CharSequence)value$; break;
    case 2: secret = (java.lang.CharSequence)value$; break;
    case 3: isApiRequest = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'questId' field.
   */
  public java.lang.CharSequence getQuestId() {
    return questId;
  }

  /**
   * Sets the value of the 'questId' field.
   * @param value the value to set.
   */
  public void setQuestId(java.lang.CharSequence value) {
    this.questId = value;
  }

  /**
   * Gets the value of the 'taskId' field.
   */
  public java.lang.CharSequence getTaskId() {
    return taskId;
  }

  /**
   * Sets the value of the 'taskId' field.
   * @param value the value to set.
   */
  public void setTaskId(java.lang.CharSequence value) {
    this.taskId = value;
  }

  /**
   * Gets the value of the 'secret' field.
   */
  public java.lang.CharSequence getSecret() {
    return secret;
  }

  /**
   * Sets the value of the 'secret' field.
   * @param value the value to set.
   */
  public void setSecret(java.lang.CharSequence value) {
    this.secret = value;
  }

  /**
   * Gets the value of the 'isApiRequest' field.
   */
  public java.lang.Boolean getIsApiRequest() {
    return isApiRequest;
  }

  /**
   * Sets the value of the 'isApiRequest' field.
   * @param value the value to set.
   */
  public void setIsApiRequest(java.lang.Boolean value) {
    this.isApiRequest = value;
  }

  /**
   * Creates a new AvroPlayboxQuest RecordBuilder.
   * @return A new AvroPlayboxQuest RecordBuilder
   */
  public static com.jivesoftware.community.cloudalytics.event.avro.AvroPlayboxQuest.Builder newBuilder() {
    return new com.jivesoftware.community.cloudalytics.event.avro.AvroPlayboxQuest.Builder();
  }
  
  /**
   * Creates a new AvroPlayboxQuest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroPlayboxQuest RecordBuilder
   */
  public static com.jivesoftware.community.cloudalytics.event.avro.AvroPlayboxQuest.Builder newBuilder(com.jivesoftware.community.cloudalytics.event.avro.AvroPlayboxQuest.Builder other) {
    return new com.jivesoftware.community.cloudalytics.event.avro.AvroPlayboxQuest.Builder(other);
  }
  
  /**
   * Creates a new AvroPlayboxQuest RecordBuilder by copying an existing AvroPlayboxQuest instance.
   * @param other The existing instance to copy.
   * @return A new AvroPlayboxQuest RecordBuilder
   */
  public static com.jivesoftware.community.cloudalytics.event.avro.AvroPlayboxQuest.Builder newBuilder(com.jivesoftware.community.cloudalytics.event.avro.AvroPlayboxQuest other) {
    return new com.jivesoftware.community.cloudalytics.event.avro.AvroPlayboxQuest.Builder(other);
  }
  
  /**
   * RecordBuilder for AvroPlayboxQuest instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroPlayboxQuest>
    implements org.apache.avro.data.RecordBuilder<AvroPlayboxQuest> {

    private java.lang.CharSequence questId;
    private java.lang.CharSequence taskId;
    private java.lang.CharSequence secret;
    private boolean isApiRequest;

    /** Creates a new Builder */
    private Builder() {
      super(com.jivesoftware.community.cloudalytics.event.avro.AvroPlayboxQuest.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.jivesoftware.community.cloudalytics.event.avro.AvroPlayboxQuest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.questId)) {
        this.questId = data().deepCopy(fields()[0].schema(), other.questId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.taskId)) {
        this.taskId = data().deepCopy(fields()[1].schema(), other.taskId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.secret)) {
        this.secret = data().deepCopy(fields()[2].schema(), other.secret);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.isApiRequest)) {
        this.isApiRequest = data().deepCopy(fields()[3].schema(), other.isApiRequest);
        fieldSetFlags()[3] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing AvroPlayboxQuest instance
     * @param other The existing instance to copy.
     */
    private Builder(com.jivesoftware.community.cloudalytics.event.avro.AvroPlayboxQuest other) {
            super(com.jivesoftware.community.cloudalytics.event.avro.AvroPlayboxQuest.SCHEMA$);
      if (isValidValue(fields()[0], other.questId)) {
        this.questId = data().deepCopy(fields()[0].schema(), other.questId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.taskId)) {
        this.taskId = data().deepCopy(fields()[1].schema(), other.taskId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.secret)) {
        this.secret = data().deepCopy(fields()[2].schema(), other.secret);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.isApiRequest)) {
        this.isApiRequest = data().deepCopy(fields()[3].schema(), other.isApiRequest);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'questId' field.
      * @return The value.
      */
    public java.lang.CharSequence getQuestId() {
      return questId;
    }

    /**
      * Sets the value of the 'questId' field.
      * @param value The value of 'questId'.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.event.avro.AvroPlayboxQuest.Builder setQuestId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.questId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'questId' field has been set.
      * @return True if the 'questId' field has been set, false otherwise.
      */
    public boolean hasQuestId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'questId' field.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.event.avro.AvroPlayboxQuest.Builder clearQuestId() {
      questId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'taskId' field.
      * @return The value.
      */
    public java.lang.CharSequence getTaskId() {
      return taskId;
    }

    /**
      * Sets the value of the 'taskId' field.
      * @param value The value of 'taskId'.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.event.avro.AvroPlayboxQuest.Builder setTaskId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.taskId = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'taskId' field has been set.
      * @return True if the 'taskId' field has been set, false otherwise.
      */
    public boolean hasTaskId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'taskId' field.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.event.avro.AvroPlayboxQuest.Builder clearTaskId() {
      taskId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'secret' field.
      * @return The value.
      */
    public java.lang.CharSequence getSecret() {
      return secret;
    }

    /**
      * Sets the value of the 'secret' field.
      * @param value The value of 'secret'.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.event.avro.AvroPlayboxQuest.Builder setSecret(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.secret = value;
      fieldSetFlags()[2] = true;
      return this; 
    }

    /**
      * Checks whether the 'secret' field has been set.
      * @return True if the 'secret' field has been set, false otherwise.
      */
    public boolean hasSecret() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'secret' field.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.event.avro.AvroPlayboxQuest.Builder clearSecret() {
      secret = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'isApiRequest' field.
      * @return The value.
      */
    public java.lang.Boolean getIsApiRequest() {
      return isApiRequest;
    }

    /**
      * Sets the value of the 'isApiRequest' field.
      * @param value The value of 'isApiRequest'.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.event.avro.AvroPlayboxQuest.Builder setIsApiRequest(boolean value) {
      validate(fields()[3], value);
      this.isApiRequest = value;
      fieldSetFlags()[3] = true;
      return this; 
    }

    /**
      * Checks whether the 'isApiRequest' field has been set.
      * @return True if the 'isApiRequest' field has been set, false otherwise.
      */
    public boolean hasIsApiRequest() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'isApiRequest' field.
      * @return This builder.
      */
    public com.jivesoftware.community.cloudalytics.event.avro.AvroPlayboxQuest.Builder clearIsApiRequest() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public AvroPlayboxQuest build() {
      try {
        AvroPlayboxQuest record = new AvroPlayboxQuest();
        record.questId = fieldSetFlags()[0] ? this.questId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.taskId = fieldSetFlags()[1] ? this.taskId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.secret = fieldSetFlags()[2] ? this.secret : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.isApiRequest = fieldSetFlags()[3] ? this.isApiRequest : (java.lang.Boolean) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
